runtime: python
api_version: 1
threadsafe: false 


runtime_config: 
  python_version: 3

handlers:
- url: .*
  script: app.py

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
