
runtime: python27
api_version: 1
threadsafe: false 


runtime_config: 
  python_version: 2


handlers:
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: flask 
  version: 0.12
